### ISSUE TITLE
Affix Error 1.19.2 Forge

### ISSUE THREAD

**Issue by Krimatoria** [Bryce792/ApotheoticAdditions#13]
Forge 43.3.5
Apotheotic_additions1.0.2_v1.19.2.jar
Placebo-1.19.2-7.3.5.jar

Mmm, there is some kind of strange error here is the log file and branches from related mods.https://github.com/SammySemicolon/Malum-Mod/issues/230
**I don't have the Malum mod installed**

[00:19:23] [Render thread/ERROR]: Failed parsing affix_loot_entries file apotheotic_additions:overworld/crude_scythe.
[00:19:23] [Render thread/ERROR]: Underlying Exception: 
java.lang.RuntimeException: Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: malum:crude_scythe
	at com.mojang.serialization.DataResult.lambda$getOrThrow$4(DataResult.java:100) ~[datafixerupper-5.0.28.jar%23126!/:?]
	at com.mojang.datafixers.util.Either$Right.map(Either.java:99) ~[datafixerupper-5.0.28.jar%23126!/:?]
	at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:93) ~[datafixerupper-5.0.28.jar%23126!/:?]
	at shadows.placebo.json.PSerializer.lambda$fromCodec$2(PSerializer.java:122) ~[Placebo-1.19.2-7.3.5.jar%23639!/:7.3.5]
	at shadows.placebo.json.PSerializer.read(PSerializer.java:76) ~[Placebo-1.19.2-7.3.5.jar%23639!/:7.3.5]
	at shadows.placebo.json.PlaceboJsonReloadListener.lambda$apply$0(PlaceboJsonReloadListener.java:99) ~[Placebo-1.19.2-7.3.5.jar%23639!/:7.3.5]
	at java.util.HashMap.forEach(Unknown Source) ~[?:?]
	at shadows.placebo.json.PlaceboJsonReloadListener.apply(PlaceboJsonReloadListener.java:91) ~[Placebo-1.19.2-7.3.5.jar%23639!/:7.3.5]
	at shadows.placebo.json.PlaceboJsonReloadListener.m_5787_(PlaceboJsonReloadListener.java:47) ~[Placebo-1.19.2-7.3.5.jar%23639!/:7.3.5]
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.Minecraft.m_18701_(Minecraft.java:5919) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233096_(WorldOpenFlows.java:130) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233122_(WorldOpenFlows.java:109) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.doLoadLevel(WorldOpenFlows.java:148) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233145_(WorldOpenFlows.java:136) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233133_(WorldOpenFlows.java:58) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_101744_(WorldSelectionList.java:586) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_101704_(WorldSelectionList.java:448) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_6375_(WorldSelectionList.java:375) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.components.AbstractSelectionList.m_6375_(AbstractSelectionList.java:336) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:27) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:88) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:522) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:85) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81) ~[lwjgl-glfw-3.3.1.jar%23144!/:build 7]
	at bre2el.fpsreducer.handler.glfw.InputEventHandler$MouseButtonEventHandler.invoke(InputEventHandler.java:133) ~[FpsReducer2-forge-1.19.2-2.1.jar%23552!/:1.19.2-2.1]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar%23144!/:build 7]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%23136!/:build 7]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar%23144!/:build 7]
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:204) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:337) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1143) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.3.5.jar%23101!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
[00:19:23] [Render thread/ERROR]: Codec failure for type Affix Loot Entry, message: Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: malum:soul_stained_steel_scythe
[00:19:23] [Render thread/ERROR]: Failed parsing affix_loot_entries file apotheotic_additions:overworld/soul_stained_steel_scythe.
[00:19:23] [Render thread/ERROR]: Underlying Exception: 
java.lang.RuntimeException: Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: malum:soul_stained_steel_scythe
	at com.mojang.serialization.DataResult.lambda$getOrThrow$4(DataResult.java:100) ~[datafixerupper-5.0.28.jar%23126!/:?]
	at com.mojang.datafixers.util.Either$Right.map(Either.java:99) ~[datafixerupper-5.0.28.jar%23126!/:?]
	at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:93) ~[datafixerupper-5.0.28.jar%23126!/:?]
	at shadows.placebo.json.PSerializer.lambda$fromCodec$2(PSerializer.java:122) ~[Placebo-1.19.2-7.3.5.jar%23639!/:7.3.5]
	at shadows.placebo.json.PSerializer.read(PSerializer.java:76) ~[Placebo-1.19.2-7.3.5.jar%23639!/:7.3.5]
	at shadows.placebo.json.PlaceboJsonReloadListener.lambda$apply$0(PlaceboJsonReloadListener.java:99) ~[Placebo-1.19.2-7.3.5.jar%23639!/:7.3.5]
	at java.util.HashMap.forEach(Unknown Source) ~[?:?]
	at shadows.placebo.json.PlaceboJsonReloadListener.apply(PlaceboJsonReloadListener.java:91) ~[Placebo-1.19.2-7.3.5.jar%23639!/:7.3.5]
	at shadows.placebo.json.PlaceboJsonReloadListener.m_5787_(PlaceboJsonReloadListener.java:47) ~[Placebo-1.19.2-7.3.5.jar%23639!/:7.3.5]
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.Minecraft.m_18701_(Minecraft.java:5919) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233096_(WorldOpenFlows.java:130) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233122_(WorldOpenFlows.java:109) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.doLoadLevel(WorldOpenFlows.java:148) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233145_(WorldOpenFlows.java:136) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233133_(WorldOpenFlows.java:58) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_101744_(WorldSelectionList.java:586) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_101704_(WorldSelectionList.java:448) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_6375_(WorldSelectionList.java:375) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.components.AbstractSelectionList.m_6375_(AbstractSelectionList.java:336) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:27) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:88) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:522) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:85) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81) ~[lwjgl-glfw-3.3.1.jar%23144!/:build 7]
	at bre2el.fpsreducer.handler.glfw.InputEventHandler$MouseButtonEventHandler.invoke(InputEventHandler.java:133) ~[FpsReducer2-forge-1.19.2-2.1.jar%23552!/:1.19.2-2.1]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar%23144!/:build 7]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%23136!/:build 7]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar%23144!/:build 7]
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:204) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:337) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1143) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.3.5.jar%23101!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]

**Comment by Krimatoria** [comment]
[Apotheosist](https://github.com/Shadows-of-Fire/Apotheosis/issues/1154#issuecomment-1934359511)

[12Feb2024 02:41:06.306] [Render thread/ERROR] [placebo/]: Codec failure for type Affix Loot Entry, message: Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: malum:soul_stained_steel_scythe

![image](https://github.com/Bryce792/ApotheoticAdditions/assets/106809386/261ecff8-f443-40c0-8124-f00cb5f04467)
