### ISSUE TITLE
1.20.1 Forge 

### ISSUE THREAD

**Issue by Krimatoria** [Bryce792/ApotheoticAdditions#30]
ApotheoticAdditionsV2.0.2.jar

> [00:21:38] [Worker-ResourceReload-0/ERROR] [ne.mi.co.ForgeHooks/]: Couldn't parse element loot_tables:apotheotic_additions:chests/ie_spawner
> --
> 4088 | java.lang.RuntimeException: Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: apotheosis:vial_of_expulsion
> 4089 | at com.mojang.serialization.DataResult.lambda$getOrThrow$5(DataResult.java:101) ~[datafixerupper-6.0.8.jar%2379!/:?] {re:mixin}
> 4090 | at com.mojang.datafixers.util.Either$Right.map(Either.java:99) ~[datafixerupper-6.0.8.jar%2379!/:?] {}
> 4091 | at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:93) ~[datafixerupper-6.0.8.jar%2379!/:?] {re:mixin}
> 4092 | at dev.shadowsoffire.placebo.loot.StackLootEntry$Serializer.deserialize(StackLootEntry.java:75) ~[Placebo-1.20.1-8.6.2.jar%23678!/:8.6.2] {re:classloading}
> 4093 | at dev.shadowsoffire.placebo.loot.StackLootEntry$Serializer.m_7267_(StackLootEntry.java:69) ~[Placebo-1.20.1-8.6.2.jar%23678!/:8.6.2] {re:classloading}
> 4094 | at net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer$Serializer.m_5921_(LootPoolSingletonContainer.java:151) ~[client-1.20.1-20230612.114412-srg.jar%23760!/:?] {re:classloading,pl:connector_pre_launch:A}
> 4095 | at net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer$Serializer.m_5921_(LootPoolSingletonContainer.java:129) ~[client-1.20.1-20230612.114412-srg.jar%23760!/:?] {re:classloading,pl:connector_pre_launch:A}
> 4096 | at net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer$Serializer.m_7561_(LootPoolEntryContainer.java:86) ~[client-1.20.1-20230612.114412-srg.jar%23760!/:?] {re:classloading,pl:connector_pre_launch:A}
> 4097 | at net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer$Serializer.m_7561_(LootPoolEntryContainer.java:74) ~[client-1.20.1-20230612.114412-srg.jar%23760!/:?] {re:classloading,pl:connector_pre_launch:A}
> 4098 | at net.minecraft.world.level.storage.loot.GsonAdapterFactory$JsonAdapter.deserialize(GsonAdapterFactory.java:102) ~[client-1.20.1-20230612.114412-srg.jar%23760!/:?] {re:classloading,pl:connector_pre_launch:A}
> 4099 | at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar%2372!/:?] {}
> 4100 | at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[gson-2.10.jar%2372!/:?] {}
> 4101 | at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.10.jar%2372!/:?] {}
> 4102 | at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar%2372!/:?] {re:mixin}
> 4103 | at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar%2372!/:?] {re:mixin}
> 4104 | at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar%2372!/:?] {re:mixin}
> 4105 | at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.jar%2372!/:?] {}
> 4106 | at net.minecraft.util.GsonHelper.m_13808_(GsonHelper.java:463) ~[client-1.20.1-20230612.114412-srg.jar%23760!/:?] {re:classloading,pl:connector_pre_launch:A,re:mixin,pl:connector_pre_launch:A}
> 4107 | at net.minecraft.util.GsonHelper.m_13836_(GsonHelper.java:471) ~[client-1.20.1-20230612.114412-srg.jar%23760!/:?] {re:classloading,pl:connector_pre_launch:A,re:mixin,pl:connector_pre_launch:A}
> 4108 | at net.minecraft.world.level.storage.loot.LootPool$Serializer.deserialize(LootPool.java:192) ~[client-1.20.1-20230612.114412-srg.jar%23760!/:?] {re:classloading,pl:connector_pre_launch:A}
> 4109 | at net.minecraft.world.level.storage.loot.LootPool$Serializer.deserialize(LootPool.java:189) ~[client-1.20.1-20230612.114412-srg.jar%23760!/:?] {re:classloading,pl:connector_pre_launch:A}
> 4110 | at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar%2372!/:?] {}
> 4111 | at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[gson-2.10.jar%2372!/:?] {}
> 4112 | at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.10.jar%2372!/:?] {}
> 4113 | at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar%2372!/:?] {re:mixin}
> 4114 | at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar%2372!/:?] {re:mixin}
> 4115 | at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar%2372!/:?] {re:mixin}
> 4116 | at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.jar%2372!/:?] {}
> 4117 | at net.minecraft.util.GsonHelper.m_13808_(GsonHelper.java:463) ~[client-1.20.1-20230612.114412-srg.jar%23760!/:?] {re:classloading,pl:connector_pre_launch:A,re:mixin,pl:connector_pre_launch:A}
> 4118 | at net.minecraft.util.GsonHelper.m_13845_(GsonHelper.java:481) ~[client-1.20.1-20230612.114412-srg.jar%23760!/:?] {re:classloading,pl:connector_pre_launch:A,re:mixin,pl:connector_pre_launch:A}
> 4119 | at net.minecraft.world.level.storage.loot.LootTable$Serializer.deserialize(LootTable.java:294) ~[client-1.20.1-20230612.114412-srg.jar%23760!/:?] {re:classloading,pl:connector_pre_launch:A}
> 4120 | at net.minecraft.world.level.storage.loot.LootTable$Serializer.deserialize(LootTable.java:291) ~[client-1.20.1-20230612.114412-srg.jar%23760!/:?] {re:classloading,pl:connector_pre_launch:A}
> 4121 | at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar%2372!/:?] {}
> 4122 | at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar%2372!/:?] {re:mixin}
> 4123 | at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar%2372!/:?] {re:mixin}
> 4124 | at com.google.gson.Gson.fromJson(Gson.java:1261) ~[gson-2.10.jar%2372!/:?] {re:mixin}
> 4125 | at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:871) ~[forge-1.20.1-47.3.5-universal.jar%23765!/:?] {re:mixin,re:classloading,pl:mixin:APP:apotheosis.mixins.json:ForgeHooksMixin from mod apotheosis,pl:mixin:APP:connectormod.mixins.json:ForgeHooksMixin from mod connectormod,pl:mixin:APP:connectormod.mixins.json:item.ForgeHooksMixin from mod connectormod,pl:mixin:APP:lootjs-forge.mixins.json:ForgeHooksMixin from mod lootjs,pl:mixin:A}
> 4126 | at net.minecraftforge.common.ForgeHooks.lambda$getLootTableDeserializer$3(ForgeHooks.java:848) ~[forge-1.20.1-47.3.5-universal.jar%23765!/:?] {re:mixin,re:classloading,pl:mixin:APP:apotheosis.mixins.json:ForgeHooksMixin from mod apotheosis,pl:mixin:APP:connectormod.mixins.json:ForgeHooksMixin from mod connectormod,pl:mixin:APP:connectormod.mixins.json:item.ForgeHooksMixin from mod connectormod,pl:mixin:APP:lootjs-forge.mixins.json:ForgeHooksMixin from mod lootjs,pl:mixin:A}
> 4127 | at net.minecraft.world.level.storage.loot.LootDataType.deserialize(LootDataType.java:45) ~[client-1.20.1-20230612.114412-srg.jar%23760!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:connector_pre_launch:A}
> 4128 | at net.minecraft.world.level.storage.loot.LootDataManager.lambda$scheduleElementParse$4(LootDataManager.java:56) ~[client-1.20.1-20230612.114412-srg.jar%23760!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:mixin:APP:fabric-resource-conditions-api-v1.mixins.json:LootManagerMixin from mod fabric_resource_conditions_api_v1,pl:mixin:APP:placebo.mixins.json:LootTablesMixin from mod placebo,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:KeyedResourceReloadListenerMixin from mod fabric_resource_loader_v0,pl:mixin:APP:puzzleslib.forge.mixins.json:LootDataManagerForgeMixin from mod puzzleslib,pl:mixin:APP:architectury.mixins.json:MixinLootDataManager from mod architectury,pl:mixin:APP:fabric-loot-api-v2.mixins.json:LootManagerMixin from mod fabric_loot_api_v2,pl:mixin:APP:kubejs-common.mixins.json:LootTablesMixin from mod kubejs,pl:mixin:APP:blueprint.mixins.json:LootDataManagerMixin from mod blueprint,pl:mixin:A,pl:connector_pre_launch:A}
> 4129 | at java.util.HashMap.forEach(Unknown Source) ~[?:?] {re:mixin}
> 4130 | at net.minecraft.world.level.storage.loot.LootDataManager.m_278660_(LootDataManager.java:55) ~[client-1.20.1-20230612.114412-srg.jar%23760!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:mixin:APP:fabric-resource-conditions-api-v1.mixins.json:LootManagerMixin from mod fabric_resource_conditions_api_v1,pl:mixin:APP:placebo.mixins.json:LootTablesMixin from mod placebo,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:KeyedResourceReloadListenerMixin from mod fabric_resource_loader_v0,pl:mixin:APP:puzzleslib.forge.mixins.json:LootDataManagerForgeMixin from mod puzzleslib,pl:mixin:APP:architectury.mixins.json:MixinLootDataManager from mod architectury,pl:mixin:APP:fabric-loot-api-v2.mixins.json:LootManagerMixin from mod fabric_loot_api_v2,pl:mixin:APP:kubejs-common.mixins.json:LootTablesMixin from mod kubejs,pl:mixin:APP:blueprint.mixins.json:LootDataManagerMixin from mod blueprint,pl:mixin:A,pl:connector_pre_launch:A}
> 4131 | at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
> 4132 | at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
> 4133 | at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
> 4134 | at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
> 4135 | at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {re:mixin,re:computing_frames}
> 4136 | at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {re:mixin,re:computing_frames}
> 4137 | at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {re:mixin}

**Comment by Krimatoria** [comment]
> <html>
> <body>
> 
> [00:21:39] [Worker-ResourceReload-0/ERROR] [ne.mi.co.ForgeHooks/]: Couldn't parse element loot_tables:apotheotic_additions:chests/born_in_chaos_spawner
> --
> 4296 | java.lang.RuntimeException: Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: apotheosis:vial_of_expulsion
> 4297 | at com.mojang.serialization.DataResult.lambda$getOrThrow$5(DataResult.java:101) ~[datafixerupper-6.0.8.jar%2379!/:?] {re:mixin}
> 4298 | at com.mojang.datafixers.util.Either$Right.map(Either.java:99) ~[datafixerupper-6.0.8.jar%2379!/:?] {}
> 4299 | at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:93) ~[datafixerupper-6.0.8.jar%2379!/:?] {re:mixin}
> 4300 | at dev.shadowsoffire.placebo.loot.StackLootEntry$Serializer.deserialize(StackLootEntry.java:75) ~[Placebo-1.20.1-8.6.2.jar%23678!/:8.6.2] {re:classloading}
> 4301 | at dev.shadowsoffire.placebo.loot.StackLootEntry$Serializer.m_7267_(StackLootEntry.java:69) ~[Placebo-1.20.1-8.6.2.jar%23678!/:8.6.2] {re:classloading}
> 4302 | at net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer$Serializer.m_5921_(LootPoolSingletonContainer.java:151) ~[client-1.20.1-20230612.114412-srg.jar%23760!/:?] {re:classloading,pl:connector_pre_launch:A}
> 4303 | at net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer$Serializer.m_5921_(LootPoolSingletonContainer.java:129) ~[client-1.20.1-20230612.114412-srg.jar%23760!/:?] {re:classloading,pl:connector_pre_launch:A}
> 4304 | at net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer$Serializer.m_7561_(LootPoolEntryContainer.java:86) ~[client-1.20.1-20230612.114412-srg.jar%23760!/:?] {re:classloading,pl:connector_pre_launch:A}
> 4305 | at net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer$Serializer.m_7561_(LootPoolEntryContainer.java:74) ~[client-1.20.1-20230612.114412-srg.jar%23760!/:?] {re:classloading,pl:connector_pre_launch:A}
> 4306 | at net.minecraft.world.level.storage.loot.GsonAdapterFactory$JsonAdapter.deserialize(GsonAdapterFactory.java:102) ~[client-1.20.1-20230612.114412-srg.jar%23760!/:?] {re:classloading,pl:connector_pre_launch:A}
> 4307 | at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar%2372!/:?] {}
> 4308 | at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[gson-2.10.jar%2372!/:?] {}
> 4309 | at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.10.jar%2372!/:?] {}
> 4310 | at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar%2372!/:?] {re:mixin}
> 4311 | at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar%2372!/:?] {re:mixin}
> 4312 | at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar%2372!/:?] {re:mixin}
> 4313 | at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.jar%2372!/:?] {}
> 4314 | at net.minecraft.util.GsonHelper.m_13808_(GsonHelper.java:463) ~[client-1.20.1-20230612.114412-srg.jar%23760!/:?] {re:classloading,pl:connector_pre_launch:A,re:mixin,pl:connector_pre_launch:A}
> 4315 | at net.minecraft.util.GsonHelper.m_13836_(GsonHelper.java:471) ~[client-1.20.1-20230612.114412-srg.jar%23760!/:?] {re:classloading,pl:connector_pre_launch:A,re:mixin,pl:connector_pre_launch:A}
> 4316 | at net.minecraft.world.level.storage.loot.LootPool$Serializer.deserialize(LootPool.java:192) ~[client-1.20.1-20230612.114412-srg.jar%23760!/:?] {re:classloading,pl:connector_pre_launch:A}
> 4317 | at net.minecraft.world.level.storage.loot.LootPool$Serializer.deserialize(LootPool.java:189) ~[client-1.20.1-20230612.114412-srg.jar%23760!/:?] {re:classloading,pl:connector_pre_launch:A}
> 4318 | at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar%2372!/:?] {}
> 4319 | at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[gson-2.10.jar%2372!/:?] {}
> 4320 | at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.10.jar%2372!/:?] {}
> 4321 | at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar%2372!/:?] {re:mixin}
> 4322 | at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar%2372!/:?] {re:mixin}
> 4323 | at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar%2372!/:?] {re:mixin}
> 4324 | at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.jar%2372!/:?] {}
> 4325 | at net.minecraft.util.GsonHelper.m_13808_(GsonHelper.java:463) ~[client-1.20.1-20230612.114412-srg.jar%23760!/:?] {re:classloading,pl:connector_pre_launch:A,re:mixin,pl:connector_pre_launch:A}
> 4326 | at net.minecraft.util.GsonHelper.m_13845_(GsonHelper.java:481) ~[client-1.20.1-20230612.114412-srg.jar%23760!/:?] {re:classloading,pl:connector_pre_launch:A,re:mixin,pl:connector_pre_launch:A}
> 4327 | at net.minecraft.world.level.storage.loot.LootTable$Serializer.deserialize(LootTable.java:294) ~[client-1.20.1-20230612.114412-srg.jar%23760!/:?] {re:classloading,pl:connector_pre_launch:A}
> 4328 | at net.minecraft.world.level.storage.loot.LootTable$Serializer.deserialize(LootTable.java:291) ~[client-1.20.1-20230612.114412-srg.jar%23760!/:?] {re:classloading,pl:connector_pre_launch:A}
> 4329 | at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar%2372!/:?] {}
> 4330 | at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar%2372!/:?] {re:mixin}
> 4331 | at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar%2372!/:?] {re:mixin}
> 4332 | at com.google.gson.Gson.fromJson(Gson.java:1261) ~[gson-2.10.jar%2372!/:?] {re:mixin}
> 4333 | at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:871) ~[forge-1.20.1-47.3.5-universal.jar%23765!/:?] {re:mixin,re:classloading,pl:mixin:APP:apotheosis.mixins.json:ForgeHooksMixin from mod apotheosis,pl:mixin:APP:connectormod.mixins.json:ForgeHooksMixin from mod connectormod,pl:mixin:APP:connectormod.mixins.json:item.ForgeHooksMixin from mod connectormod,pl:mixin:APP:lootjs-forge.mixins.json:ForgeHooksMixin from mod lootjs,pl:mixin:A}
> 4334 | at net.minecraftforge.common.ForgeHooks.lambda$getLootTableDeserializer$3(ForgeHooks.java:848) ~[forge-1.20.1-47.3.5-universal.jar%23765!/:?] {re:mixin,re:classloading,pl:mixin:APP:apotheosis.mixins.json:ForgeHooksMixin from mod apotheosis,pl:mixin:APP:connectormod.mixins.json:ForgeHooksMixin from mod connectormod,pl:mixin:APP:connectormod.mixins.json:item.ForgeHooksMixin from mod connectormod,pl:mixin:APP:lootjs-forge.mixins.json:ForgeHooksMixin from mod lootjs,pl:mixin:A}
> 4335 | at net.minecraft.world.level.storage.loot.LootDataType.deserialize(LootDataType.java:45) ~[client-1.20.1-20230612.114412-srg.jar%23760!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:connector_pre_launch:A}
> 4336 | at net.minecraft.world.level.storage.loot.LootDataManager.lambda$scheduleElementParse$4(LootDataManager.java:56) ~[client-1.20.1-20230612.114412-srg.jar%23760!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:mixin:APP:fabric-resource-conditions-api-v1.mixins.json:LootManagerMixin from mod fabric_resource_conditions_api_v1,pl:mixin:APP:placebo.mixins.json:LootTablesMixin from mod placebo,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:KeyedResourceReloadListenerMixin from mod fabric_resource_loader_v0,pl:mixin:APP:puzzleslib.forge.mixins.json:LootDataManagerForgeMixin from mod puzzleslib,pl:mixin:APP:architectury.mixins.json:MixinLootDataManager from mod architectury,pl:mixin:APP:fabric-loot-api-v2.mixins.json:LootManagerMixin from mod fabric_loot_api_v2,pl:mixin:APP:kubejs-common.mixins.json:LootTablesMixin from mod kubejs,pl:mixin:APP:blueprint.mixins.json:LootDataManagerMixin from mod blueprint,pl:mixin:A,pl:connector_pre_launch:A}
> 4337 | at java.util.HashMap.forEach(Unknown Source) ~[?:?] {re:mixin}
> 4338 | at net.minecraft.world.level.storage.loot.LootDataManager.m_278660_(LootDataManager.java:55) ~[client-1.20.1-20230612.114412-srg.jar%23760!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:mixin:APP:fabric-resource-conditions-api-v1.mixins.json:LootManagerMixin from mod fabric_resource_conditions_api_v1,pl:mixin:APP:placebo.mixins.json:LootTablesMixin from mod placebo,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:KeyedResourceReloadListenerMixin from mod fabric_resource_loader_v0,pl:mixin:APP:puzzleslib.forge.mixins.json:LootDataManagerForgeMixin from mod puzzleslib,pl:mixin:APP:architectury.mixins.json:MixinLootDataManager from mod architectury,pl:mixin:APP:fabric-loot-api-v2.mixins.json:LootManagerMixin from mod fabric_loot_api_v2,pl:mixin:APP:kubejs-common.mixins.json:LootTablesMixin from mod kubejs,pl:mixin:APP:blueprint.mixins.json:LootDataManagerMixin from mod blueprint,pl:mixin:A,pl:connector_pre_launch:A}
> 4339 | at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
> 4340 | at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
> 4341 | at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
> 4342 | at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
> 4343 | at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {re:mixin,re:computing_frames}
> 4344 | at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {re:mixin,re:computing_frames}
> 4345 | at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {re:mixin}
> 
> 
> </body>
> </html>

**Comment by Krimatoria** [comment]
[00:21:40] [Render thread/ERROR] [minecraft/RecipeManager]: Parsing error loading recipe apotheotic_additions:reforging/ancient: com.google.gson.JsonSyntaxException: Missing sigil_cost, expected to find a Int
--

**Comment by expdani** [comment]
Same problem on forge 1.20.1.
