### ISSUE TITLE
Errored Gate Pearl recipe | apotheoticadditions:gateways/boss_gate_small

### ISSUE THREAD

**Issue by Octelly** [Bryce792/ApotheoticAdditions#37]
#27 might be related, but I simply cannot tell from the information provided.

![Screenshot_20240924_083349](https://github.com/user-attachments/assets/93bef6bb-8314-4019-ac4e-eac481304801)

**Comment by BrettMoan** [comment]
Also having this error. 

i hopped into creative to cheat the pearl in, and it has no effect currently.

the versions of 
- gateways to eternity is 1.19.2-3.2.3
- apotheosis is 1.19.2-6.5.2
- apotheotic additions is 1.0.4




here is the stack trace

```
[19:01:30] [Server thread/ERROR]:Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemOnPacket@506c6703, suppressing errorjava.lang.NullPointerException: Cannot invoke "shadows.gateways.gate.Gateway.getId()" because "gate" is null
	at shadows.gateways.entity.GatewayEntity.<init>(GatewayEntity.java:89) ~[GatewaysToEternity-1.19.2-3.2.3.jar%23820!/:3.2.3]
	at shadows.gateways.item.GatePearlItem.m_6225_(GatePearlItem.java:39) ~[GatewaysToEternity-1.19.2-3.2.3.jar%23820!/:3.2.3]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:675) ~[forge-1.19.2-43.3.8-universal.jar%231088!/:?]
	at net.minecraft.world.item.ItemStack.m_41661_(ItemStack.java:236) ~[client-1.19.2-20220805.130853-srg.jar%231083!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:352) ~[client-1.19.2-20220805.130853-srg.jar%231083!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:1060) ~[client-1.19.2-20220805.130853-srg.jar%231083!/:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:34) ~[client-1.19.2-20220805.130853-srg.jar%231083!/:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[client-1.19.2-20220805.130853-srg.jar%231083!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.19.2-20220805.130853-srg.jar%231083!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.19.2-20220805.130853-srg.jar%231083!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.19.2-20220805.130853-srg.jar%231083!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.19.2-20220805.130853-srg.jar%231083!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:763) ~[client-1.19.2-20220805.130853-srg.jar%231083!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:157) ~[client-1.19.2-20220805.130853-srg.jar%231083!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.19.2-20220805.130853-srg.jar%231083!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:746) ~[client-1.19.2-20220805.130853-srg.jar%231083!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740) ~[client-1.19.2-20220805.130853-srg.jar%231083!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[client-1.19.2-20220805.130853-srg.jar%231083!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:726) ~[client-1.19.2-20220805.130853-srg.jar%231083!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:658) ~[client-1.19.2-20220805.130853-srg.jar%231083!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%231083!/:?]
```

**Comment by BrettMoan** [comment]
I'd like to note: that this behavior doesn't seem to exist on mc 1.20.1 versions in a different combination of mods:
- gateways to eternity 1.20.1-4-2-4
- apotheosis 1.20.1-7.3.4
- apotheotic additions v2.0.2

while it would be super awesome to patch this in the 1.19 version of the mods, i can at least confirm Ive had the portal working in 1.20
