### ISSUE TITLE
Game crashes when socketing "esoteric"-level gems

### ISSUE THREAD

**Issue by SonyStinks** [Bryce792/ApotheoticAdditions#9]
Gems were crafted on the Apotheosis Gem Cutting Table. Rather disappointing result after painstakingly collecting 32 of them--and sacrificing all that artifact-level stuff--to see what top-tier gems would work like.

Item to be socketed: Cheljen's Windswept Recurve Bow of the Ranger
Item rarity: rare
Number of sockets: 2

Minecraft version: 1.20.1
Forge version: 47.2.19
Java version: 18.0.1.1, Oracle Corporation
OS: Linux (amd64) version 6.5.0-15-generic (Ubuntu 22.04 LTS)

This is NOT a conflict with another mod. This crash IS reproducible:

1) Install Apotheosis/Patchouli/etc. and Apotheotic Additions v1.3
2) Get/make an affixed item (rarity: rare)
3) Get/make ANY esoteric-level gem
4) Attempt to socket the gem into the item
5) Game crash occurs when the mouse pointer moves over the output item, or when the output item enters the player's hand.

Crash logs indicate a problem with "ticking player":
`Description: Ticking player
java.lang.NullPointerException: Cannot invoke "dev.shadowsoffire.placebo.util.StepFunction.get(float)" because the return value of "java.util.Map.get(Object)" is null
	at dev.shadowsoffire.apotheosis.adventure.affix.socket.gem.bonus.AttributeBonus.read(AttributeBonus.java:76) ~[Apotheosis-1.20.1-7.2.2.jar%23340!/:7.2.2] {re:classloading}
	at dev.shadowsoffire.apotheosis.adventure.affix.socket.gem.bonus.AttributeBonus.addModifiers(AttributeBonus.java:49) ~[Apotheosis-1.20.1-7.2.2.jar%23340!/:7.2.2] {re:classloading}
	at dev.shadowsoffire.apotheosis.adventure.affix.socket.gem.GemInstance.lambda$addModifiers$0(GemInstance.java:94) ~[Apotheosis-1.20.1-7.2.2.jar%23340!/:7.2.2] {re:classloading}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin,re:computing_frames}
	at dev.shadowsoffire.apotheosis.adventure.affix.socket.gem.GemInstance.ifPresent(GemInstance.java:203) ~[Apotheosis-1.20.1-7.2.2.jar%23340!/:7.2.2] {re:classloading}
	at dev.shadowsoffire.apotheosis.adventure.affix.socket.gem.GemInstance.addModifiers(GemInstance.java:94) ~[Apotheosis-1.20.1-7.2.2.jar%23340!/:7.2.2] {re:classloading}
	at dev.shadowsoffire.apotheosis.adventure.affix.socket.SocketAffix.lambda$addModifiers$0(SocketAffix.java:63) ~[Apotheosis-1.20.1-7.2.2.jar%23340!/:7.2.2] {re:classloading}`

Esoteric-level gems are also missing their effects and stat bonus information in their tooltips. This MAY be related to the problem. If so, it also affects Heirloom and Artifact level gems as well.

Feel free to contact me for more information about this bug.

**Comment by Bryce792** [comment]
Was able to discover whilst testing that some gems added by Apotheosis work, whilst the first gem I tested with (Hearty) from Apotheotic Additions crashed the game the second it was put in the gem cutting table. Even moving your mouse over the item creates a crash when the tooltip tries to load. In order to counteract this, stray away from esoteric gems unless they specifically currently already have that rarity (Any Cosmic Jewel in JEI), and I can add in upgrades for all the other gems in relative time.

**Comment by SonyStinks** [comment]
Ooh, that's a shame. Was looking forward to seeing what sort of ridiculously overpowered things I could do with a Lightning Gem and a Gem of the Samurai in my shiny bow.

I hope you find the source of the problem. Let me know if there's something I can test on this.

**Comment by SonyStinks** [comment]
I think I found part of the problem...

Apotheosis mod is TOUCHY! with its rarities. Even found a few bug issues they had to address with it.
It seems the fault lies with the Reforging Table itself. It's simply rejecting all rarities above Mythic at the moment. I can't figure out how to get the higher rarities to register properly to check this further, either. None of the higher gems are showing up in JEI even if they can exist in-game. That alone could be the real problem, for all I know.

I don't know if that's something you can work on and alter or not, but there it is. None of the shiny new rarity materials in Apotheotic Additions can be used at the moment because the Table is "somehow" putting a stop to it. Perhaps you can make your own "improved" Reforging Table instead?

If that sounds like a good idea to you, I'll go one step further and offer to help you make the texture for it, though my textures aren't all that great-looking.

Keep up the good work.
